routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/Welcome', function () {
    return view('welcome');

});

Route::get('/', 'PagesController@getNewMain');

Route::resource('proizvodi','ProizvodiController');

Route::resource('pdf','PdfController');

Route::resource('galerija','GalleryController');

Route::resource('laminat','LaminatController');

Route::resource('stakleni','StakleniController');

Route::resource('lajsni','LajsniController');

Route::resource('ostanato','OstanatoController');

Route::resource('akcii','AkciiController');

Route::get('/informacii', 'PagesController@getInformacii');

Route::get('/contact', 'PagesController@getContact');

Route::post('/contact', 'PagesController@postContact');

Route::get('/sorabotka', 'PagesController@getSorabotka');

Route::post('/sorabotka', 'PagesController@postSorabotka');

Route::get('/template', 'PagesController@template');


Auth::routes(['register'=>true]);

Route::get('/home', 'HomeController@index')->name('home');


//STARI OVDEKA

Route::get('/main', 'PagesController@getMain');

app/Http/Controllers/AkciiController.php
<?php

namespace App\Http\Controllers;

use App\Akcija;
use App\Http\Requests\CreateAkciiRequest;
use App\Http\Requests\UpdateAkciiRequest;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Session;

class AkciiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    public function index()
    {
        $akcii = Akcija::orderBy('id', 'desc')->paginate(6);

        return view('akcii.index', compact('akcii'));
    }

    public function create()
    {
        return view('akcii.create');
    }

    public function store(CreateAkciiRequest $request)
    {

        $image = $request->file('image');

        $slug = str_slug($request->title);

        if (isset($image)) {
            $imagename = $slug . '.' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!file_exists('uploads/akcii')) {
                mkdir('uploads/akcii', 0777, true);
            }
            $image->move('uploads/akcii', $imagename);
        } else {
            $imagename = 'default.png';
        }


        $akcii = new Akcija;
        $akcii->title = $request->title;
        $akcii->image = $imagename;
        $akcii->body = $request->body;
        $akcii->price = $request->price;

        $akcii->save();

        Session::flash('success', 'Uspesno vnesuvajne');
        return redirect()->route('akcii.show', $akcii->id);
    }

    public function show($id)
    {
        $akcii = Akcija::findOrFail($id);

        return view('akcii.show')->with('akcii', $akcii);
    }

    public function edit($id)
    {
        $akcii = Akcija::find($id);

        return view('akcii.edit', compact('akcii'));
    }

    public function update(UpdateAkciiRequest $request, $id)
    {
        $akcii = Akcija::find($id);

              $image = $request->file('image');

        $slug = str_slug($request->title);

        if (isset($image)) {
            $imagename = $slug . '.' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!file_exists('uploads/akcii')) {
                mkdir('uploads/akcii', 0777, true);
            }
            unlink('uploads/akcii/' . $akcii->image);
            $image->move('uploads/akcii', $imagename);
        } else {
            $imagename = $akcii->image;
        }

        $akcii->title = $request->input('title');
        $akcii->image = $imagename;
        $akcii->body = $request->input('body');
        $akcii->price = $request->input('price');


        $akcii->save();


        Session::flash('success', 'Uspesno editirajne');

        return redirect()->route('akcii.show', $akcii->id);

    }

    public function destroy($id)
    {
        $akcii = Akcija::find($id);

        if (file_exists('uploads/akcii/' . $akcii->image)) {
            unlink('uploads/akcii/' . $akcii->image);
        }
        $akcii->delete();

        Session::flash('success', 'Uspesno brisejne');

        return redirect()->route('proizvodi.index');
    }
}

resources/views/Akcii/create.blade.php
@extends('NewDesign.template')

@section('title','Akcii-create')

    @section('create-content')

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1>Креирај Нова Акција</h1>
                <hr>
                <form method="POST" enctype="multipart/form-data" action="{{ route('akcii.store') }}">
                    @csrf

                    <div class="form-group">
                        <label name="title">Наслов:</label>
                        <input id="title" type="text" name="title"
                               class="form-control{{$errors->has('title') ? 'is-invalid' : ''}}"
                               value="{{ old('title') }}"
                               autocomplete="title" autofocus required>
                        @if($errors->has('title'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('title') }}</strong>
                            </span>

                        @endif
                    </div>


                    <div class="form-group">
                        <label name="price">Цена:</label>
                        <input id="price" type="text" name="price"
                               class="form-control{{$errors->has('price') ? 'is-invalid' : ''}}"
                               value="{{ old('price') }}"
                               autocomplete="price" autofocus required>
                        @if($errors->has('price'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('price') }}</strong>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label name="title">Дополнителни инфромации:</label>
                        <textarea id="body" type="text" name="body"
                               class="form-control{{$errors->has('body') ? 'is-invalid' : ''}}"
                               value="{{ old('body') }}"
                                  autocomplete="body" autofocus required> </textarea>
                        @if($errors->has('body'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('body') }}</strong>
                            </span>

                        @endif
                    </div>

                    <div class="row">
                        <label for="image" class="col-md-4 col-form-label" >Слика:</label>
                        <input type="file" class="form-control-file" id="image" name="image" required>
                        @if($errors->has('image'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('image') }}</strong>
                            </span>
                        @endif
                    </div>

                    <input type="submit" value="Креирај Акција" class="btn btn-success btn-lg btn-block">
                    <br>
                    <br>
                    <br>
                </form>
            </div>
        </div>


    @endsection

resources/views/Akcii/edit.blade.php
@extends ('NewDesign.template')

@section('title','Akcii-edit')

@section('create-content')
    <section class="page-title" style="background-image:url(images/title/2.jpg);">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Title -->
                <div class="title-column col-md-6 col-sm-8 col-xs-12">
                    <h1>Акции</h1>
                </div>
                <!--Bread Crumb -->
                <div class="breadcrumb-column col-md-6 col-sm-4 col-xs-12">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{{url('/')}}">Почетна</a></li>
                        <li class="active">Акции</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-md-12">
                {!! Form::model($akcii, ['route' => ['akcii.update', $akcii->id],'method'=>'PUT','enctype'=>"multipart/form-data" ]) !!}
                <div class="container-fluid padding">
                    <div class="row padding">
                        <div class="col-md-8">
                        {{ Form::label('title', 'Наслов:') }}
                        {{ Form::text('title', null, ["class" => 'form-control']) }}


                        {{ Form::label('price', 'Цена:') }}
                        {{ Form::text('price', null, ["class" => 'form-control']) }}

                        {{ Form::label('body', 'Детални информации') }}
                        {{ Form::textarea('body', null, ["class" => 'form-control']) }}

                        {{ Form::label('image', 'Слика') }}
                        {{ Form::file('image', null, ["class" => 'form-control']) }}


                    </div>
                    <div class="col-md-4">
                        <div class="well">
                            <dl class="dl-horizontal">
                                <dt>Креирано на:</dt>
                                <dd>{{date('M j, Y H:i',strtotime($akcii->created_at))}}</dd>
                            </dl>

                            <dl class="dl-horizontal">
                                <dt>Последна промена на:</dt>
                                <dd>{{date('M j, Y H:i',strtotime($akcii->updated_at))}}</dd>
                            </dl>
                            <hr>

                            <div class="row">
                                <div class="col-sm-6">
                                    <a href="{{route('akcii.show',$akcii->id)}}"
                                       class="btn btn-danger btn-block">Откажи</a>

                                </div>

                                <div class="col-sm-6">
                                    {{Form::submit('Зачувајги промените',['class'=>'btn btn-success btn-block',])}}
                                </div>
                            </div>


                        </div>


                    </div>
                    {!! Form::close()!!}
                </div>
            </div>






@endsection

resources/views/Akcii/index.blade.php
@extends ('NewDesign.template')
@section('title','Akcii')

@section('create-content')

    <section class="page-title" style="background-image:url(images/title/2.jpg);">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Title -->
                <div class="title-column col-md-6 col-sm-8 col-xs-12">
                    <h1>Акции</h1>
                </div>
                <!--Bread Crumb -->
                <div class="breadcrumb-column col-md-6 col-sm-4 col-xs-12">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{{url('/')}}">Почетна</a></li>
                        <li class="active">Акции</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <br>
    <br>

    <div class="container-fluid padding">
        @auth
            <div class="col-md-2 offset-10">
                <a href="{{route("akcii.create")}}" class="btn btn-info">Креирај нова акција</a>
            </div>
        @endauth
    </div>

    <section class="">
        <div class="auto-container">
            <!--Sec Title-->
            <div class="row clearfix">
            @if($akcii->count())
                    <div class="container-fluid padding">
                        <div class="col-md-12" id="akcii">
                            <h2 class="text-center">Во продолжение можете да ги видите сите производи кои се на попуст/акција.</h2>
                        </div>
                    </div>
                    <br>
                    <br>
                @foreach($akcii as $akcija)
                    <!--Services Block-->
                        <div class="services-block col-md-4 col-sm-6 col-xs-12" style="margin-top: 25px;margin-bottom: 25px">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="{{url('akcii/'.$akcija->id)}}"><img
                                            src="{{asset('uploads/akcii/'.$akcija->image)}}" style="height: 400px;width: 400px; object-fit: cover"
                                            alt=""/></a>
                                </div>
                                <div class="lower-box">
                                    <div class="content">
                                        <a href="{{url('akcii/'.$akcija->id)}}" class="arrow-box"><span
                                                class="fa fa-angle-right"></span></a>
                                        <h3><a href="{{url('akcii/'.$akcija->id)}}">{{$akcija->title}}</a></h3>
                                        <div class="text">{{$akcija->price}} денари</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
            </div>
        </div>
        @else
            <div class="container-fluid padding">
                <div class="col-md-12">
                    <h1 class="text-center">Во Моментов Нема Производи На Акција.</h1>
                </div>
        @endif
    </section>

    <div class="text-center">
        {!! $akcii->links()!!}
    </div>
<br>
<br>

@endsection

resources/views/Akcii/show.blade.php
@extends ('NewDesign.template')

@section('title','Akcii-show')
@section('_pagetitle')
    <section class="page-title" style="background-image:url(../images/title/2.jpg);">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Title -->
                <div class="title-column col-md-6 col-sm-8 col-xs-12">
                    <h1>{{$akcii->title}}</h1>
                </div>
                <!--Bread Crumb -->
                <div class="breadcrumb-column col-md-6 col-sm-4 col-xs-12">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{{url('/')}}">Почетна</a></li>
                        <li class="active">Акции</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('create-content')
<br>
<!--Sidebar Page Container-->
<div class="sidebar-page-container">
    <div class="auto-container">
        <div class="row clearfix">
            <!--Sidebar Side-->
            <div class="sidebar-side col-lg-4 col-md-4 col-sm-12 col-xs-12">

                <aside class="sidebar default-sidebar with-padding">

                    <!-- Sidebar Category -->
                    <div class="sidebar-widget sidebar-category">
                        <ul class="list">
                            <li><a href="{{url('/')}}">Почетна</a></li>
                            <li><a href="{{url('/akcii')}}">Акции</a></li>
                            <li><a href="{{url('/laminat')}}">Ламинат</a></li>
                            <li><a href="{{url('/pdf/1')}}">Внатрешни Врати</a></li>
                            <li><a href="{{url('/pdf/2')}}">Надворешни Врати</a></li>
                            <li><a href="{{url('/stakleni')}}">Стаклени Блокови</a></li>
                            <li><a href="{{url('/galerija')}}">Галерија</a></li>
                            <li><a href="{{url('/informacii')}}">Инфромации</a></li>
                            <li><a href="{{url('/kontakt')}}">Контакт</a></li>
                        </ul>
                    </div>

                    @auth
                            <div class="well">
                                <dl class="dl-horizontal">

                                    <dt>Креирано на:</dt>
                                    <dd>{{date('M j, Y H:i',strtotime($akcii->created_at))}}</dd>
                                </dl>

                                <dl class="dl-horizontal">
                                    <dt>Последна промена на:</dt>
                                    <dd>{{date('M j, Y H:i',strtotime($akcii->updated_at))}}</dd>
                                </dl>
                                <hr>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <a href="{{route('akcii.edit',$akcii->id)}}" class="btn btn-primary btn-block">Промени</a>

                                    </div>

                                    <div class="col-sm-6">

                                        {!!Form::open(['route'=>['akcii.destroy',$akcii->id],'method'=>'DELETE','enctype'=>"multipart/form-data"])!!}

                                        {!!Form::submit('Избриши',['class'=>'btn btn-danger btn-block'])!!}

                                        {!!Form::close()!!}

                                    </div>
                                </div>
                            </div>
                    @endauth


                </aside>
            </div>
            <!--Content Side-->
            <div class="content-side col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <!--Services Single-->
                <div class="service-single">
                    <div class="inner-box">
                        <div class="image">
                            <h3 class="text-center">{{$akcii->title}}</h3>
                            <img src="{{asset('uploads/akcii/'.$akcii->image)}}" alt="" style="height: 400px;width: 700px; object-fit: cover"/>
                        </div>
                        <div class="lower-content">
                            <h3>Детални Информации</h3>
                            <div class="text">
                                <p>{{$akcii->body}}</p>
                                <h3>Цена</h3>
                                <p>{{$akcii->price}} денари</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

    {{--<div class="container-fluid padding">
        <div class="col-md-12">
            <div class="panel panel-default">
                @if(!$akcii)
                    <div>
                        <h1>Во овој момент нема производи на акција.</h1>
                    </div>
                @else
                    <div class="panel-body">
                        <div class="col-md-4">
                            <ul class="list-group">
                                <h2 class="text-center">Додатни информации:</h2>
                                <li class="list-group-item">Име:{{ $akcii->title }}</li>
                                <li class="list-group-item">Цена:{{ $akcii->price }}</li>
                                <textarea class="lead">{{$akcii->body}}</textarea>
                            </ul>

                        </div>

                        <div class="col-md-8">
                            <div class="list-group">
                                <img src="/storage/uploads/{{ $akcii->image }}"/>
                            </div>

                        </div>
                    </div>
            </div>
        </div>
        @auth
            <div class="col-md-4">
                <div class="well">
                    <dl class="dl-horizontal">
                        <dt>Креирано на:</dt>
                        <dd>{{date('M j, Y H:i',strtotime($akcii->created_at))}}</dd>
                    </dl>

                    <dl class="dl-horizontal">
                        <dt>Последна промена на:</dt>
                        <dd>{{date('M j, Y H:i',strtotime($akcii->updated_at))}}</dd>
                    </dl>
                    <hr>

                    <div class="row">
                        <div class="col-sm-6">
                            <a href="{{route('akcii.edit',$akcii->id)}}" class="btn btn-primary btn-block">Промени</a>

                        </div>

                        <div class="col-sm-6">

                            {!!Form::open(['route'=>['akcii.destroy',$akcii->id],'method'=>'DELETE','enctype'=>"multipart/form-data"])!!}

                            {!!Form::submit('Избриши',['class'=>'btn btn-danger btn-block'])!!}

                            {!!Form::close()!!}
                            @endauth
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
--}}

@endsection