routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/Welcome', function () {
    return view('welcome');

});

Route::get('/', 'PagesController@getNewMain');

Route::resource('proizvodi','ProizvodiController');

Route::resource('pdf','PdfController');

Route::resource('galerija','GalleryController');

Route::resource('laminat','LaminatController');

Route::resource('stakleni','StakleniController');

Route::resource('lajsni','LajsniController');

Route::resource('ostanato','OstanatoController');

Route::resource('akcii','AkciiController');

Route::get('/informacii', 'PagesController@getInformacii');

Route::get('/contact', 'PagesController@getContact');

Route::post('/contact', 'PagesController@postContact');

Route::get('/sorabotka', 'PagesController@getSorabotka');

Route::post('/sorabotka', 'PagesController@postSorabotka');

Route::get('/template', 'PagesController@template');


Auth::routes(['register'=>true]);

Route::get('/home', 'HomeController@index')->name('home');


//STARI OVDEKA

Route::get('/main', 'PagesController@getMain');

app/Proizvodi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Proizvodi extends Model
{
    protected $table='proizvodis';
    //protected $appends=['link'];
    const KATEGORIJA_PDF=1;
    const KATEGORIJA_LAJSNI=4;
    const KATEGORIJA_STAKLENI=5;
    const KATEGORIJA_Laminat=3;
    const KATEGORIJA_PDF_nadvoresni=2;
    const KATEGORIJA_Ostanato=6;
    public function pdfs()
    {
        return $this->hasOne('App\Pdf');
    }
    public function  link(){
        switch ($this->id)
        {
            case self::KATEGORIJA_PDF:
                return route('pdf.show',$this->id);

            case self::KATEGORIJA_Laminat:
                return route('laminat.index');

            case self::KATEGORIJA_PDF_nadvoresni:
                return route('pdf.show',$this->id);

            case self::KATEGORIJA_Ostanato:
                return route('ostanato.index');

            case self::KATEGORIJA_LAJSNI:
                return route('lajsni.index');

            case self::KATEGORIJA_STAKLENI:
                return route('stakleni.index');
        }
        return '';
    }
}

app/Http/Controllers/ProizvodiController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\CreateProizvodiRequest;
use App\Http\Requests\UpdateProizvodiRequest;
use App\Proizvodi;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
Use Session;
class ProizvodiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth',['except'=>['index']]);
    }

    public function index()
    {
        $proizvodi=Proizvodi::all();

        return view('proizvodi.index', compact('proizvodi'));

    }

    public function create()
    {
    return view('proizvodi.create');
    }

    public function store(CreateProizvodiRequest $request)
    {
        $slug = str_slug($request->title);

        $image = $request->file('image');

        if (isset($image)) {
            $imagename = $slug . '.' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!file_exists('uploads/proizvodi')) {
                mkdir('uploads/proizvodi', 0777, true);
            }
            $image->move('uploads/proizvodi', $imagename);
        } else {
            $imagename = 'default.png';
        }
        $proizvodi=new Proizvodi;

        $proizvodi->title=$request->title;
        $proizvodi->body=$request->body;
        $proizvodi->image=$imagename;
        $proizvodi->save();

        Session::flash('success','Uspesno vnesuvajne');
        return redirect()->route('proizvodi.show',$proizvodi->id);

    }

    public function show($id)
    {
        $proizvodi=Proizvodi::find($id);


        return view('proizvodi.show')->with('proizvodi',$proizvodi);
    }

    public function edit($id)
    {
        $proizvodi=Proizvodi::find($id);

        return view('proizvodi.edit',compact('proizvodi'));
    }

    public function update(UpdateProizvodiRequest $request, $id)
    {
        $proizvodi=Proizvodi::find($id);

        $proizvodi->title=$request->input('title');

        $proizvodi->body=$request->input('body');

        $image = $request->file('image');

        $slug = str_slug($request->title);

        if (isset($image)) {
            $imagename = $slug . '.' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!file_exists('uploads/proizvodi')) {
                mkdir('uploads/proizvodi', 0777, true);
            }
            unlink('uploads/proizvodi/' . $proizvodi->image);
            $image->move('uploads/proizvodi', $imagename);
        } else {
            $imagename = $proizvodi->image;
        }

        $proizvodi->image=$imagename;

        $proizvodi->save();

        Session::flash('success','Uspesno editirajne');

        return redirect()->route('proizvodi.show',$proizvodi->id);

    }

    public function destroy($id)
    {
        $proizvodi=Proizvodi::find($id);
        if (file_exists('uploads/proizvodi/' . $proizvodi->image)) {
            unlink('uploads/proizvodi/' . $proizvodi->image);
        }
        $proizvodi->delete();

        Session::flash('success','Uspesno brisejne');

        return redirect()->route('proizvodi.index');
    }
}

resources/views/Proizvodi/create.blade.php
@extends ('NewDesign.template')
@section('title','Proizvodi-create')


@section('create-content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Креирај нов Производ</h1>
            <hr>
            <form method="POST" enctype="multipart/form-data" action="{{ route('proizvodi.store') }}">
                @csrf
                <div class="form-group">
                    <label name="title">Наслов:</label>
                    <input id="title" type="text" name="title"
                           class="form-control{{$errors->has('title') ? 'is-invalid' : ''}}"
                           value="{{ old('title') }}"
                           autocomplete="title" autofocus>
                    @if($errors->has('title'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('title') }}</strong>
                            </span>

                    @endif
                </div>
                <div class="form-group">
                    <label name="body">Опис:</label>
                    <textarea id="body" type="text" name="body"
                              class="form-control{{$errors->has('body') ? 'is-invalid' : ''}}"
                              value="{{ old('body') }}"
                              autocomplete="body" autofocus> </textarea>
                    @if($errors->has('body'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('body') }}</strong>
                            </span>

                    @endif
                </div>
                <div class="row">
                    <label for="image" class="col-md-4 col-form-label">Прикачи слика:</label>
                    <input type="file" class="form-control-file" id="image" name="image">
                    @if($errors->has('image'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('image') }}</strong>
                            </span>

                    @endif
                </div>
                <input type="submit" value="Креирај" class="btn btn-success btn-lg btn-block">
            </form>
        </div>
    </div>
@endsection

resources/views/Proizvodi/edit.blade.php
@extends ('NewDesign.template')
@section('title','Proizvodi-edit')


@section('create-content')

    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-md-12">
                {!! Form::model($proizvodi, ['route' => ['proizvodi.update', $proizvodi->id],'method'=>'PUT','enctype'=>"multipart/form-data" ]) !!}
                <div class="container-fluid padding">
                    <div class="row padding">
                        <div class="col-md-8">
                            {{ Form::label('title', 'Наслов:') }}
                            {{ Form::text('title', null, ["class" => 'form-control']) }}

                            {{ Form::label('body', 'Опис') }}
                            {{ Form::textarea('body', null, ["class" => 'form-control']) }}

                            {{ Form::label('image', 'Слика') }}
                            {{ Form::file('image', null, ["class" => 'form-control']) }}

                        </div>

                        <div class="col-md-4">
                            <div class="well">
                                <dl class="dl-horizontal">
                                    <dt>Креирано На:</dt>
                                    <dd>{{date('M j, Y H:i',strtotime($proizvodi->created_at))}}</dd>
                                </dl>

                                <dl class="dl-horizontal">
                                    <dt>Последна промена на:</dt>
                                    <dd>{{date('M j, Y H:i',strtotime($proizvodi->updated_at))}}</dd>
                                </dl>
                                <hr>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <a href="{{route('proizvodi.show',$proizvodi->id)}}"
                                           class="btn btn-danger btn-block">Откажи</a>

                                    </div>

                                    <div class="col-sm-6">
                                        {{Form::submit('Зачувајги промените',['class'=>'btn btn-success btn-block',])}}

                                    </div>
                                </div>


                            </div>


                        </div>
                    </div>
                </div>
                {!! Form::close()!!}
            </div>
        </div>



@endsection

resources/views/Proizvodi/index.blade.php
@extends ('NewDesign.template')
@section('title','Proizvodi-index')
@section('_pagetitle')
    <section class="page-title" style="background-image:url(images/title/2.jpg);">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Title -->
                <div class="title-column col-md-6 col-sm-8 col-xs-12">
                    <h1>Производи</h1>
                </div>
                <!--Bread Crumb -->
                <div class="breadcrumb-column col-md-6 col-sm-4 col-xs-12">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{{url('/')}}">Почетна</a></li>
                        <li class="active">Производи</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('create-content')

    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-md-10">

            </div>
            @auth
                <div class="col-md-2">

                    <a href="{{route("proizvodi.create")}}" class="btn btn-info">Креирај Нов Производ</a>
                </div>
            @endauth
        </div>
    </div>
    <section class="services-section-two">
        <div class="auto-container">
            <!--Sec Title-->
            <div class="sec-title centered">
                <h2>Производи</h2>
            </div>
            <div class="row clearfix">
            @foreach($proizvodi as $proizvodis)
                <!--Services Block-->
                    <div class="services-block col-md-4 col-sm-6 col-xs-12" style="margin-top: 25px;margin-bottom: 25px">
                        <div class="inner-box">
                            <div class="image">
                                <a href="{{url('ostanato/'.$proizvodis->id)}}"><img
                                        src="{{asset('uploads/proizvodi/'.$proizvodis->image)}}" style="height: 400px;width: 400px; object-fit: cover"
                                        alt=""/></a>
                            </div>
                            <div class="lower-box">
                                <div class="content">
                                    <a href="{{$proizvodis->link()}}" class="arrow-box"><span
                                            class="fa fa-angle-right"></span></a>
                                    <div class="text"><h2>{{$proizvodis->title}}</h2></div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
@endsection

resources/views/Proizvodi/show.blade.php
@extends ('NewDesign.template')
@section('title','Proizvodi-show')


@section('create-content')


    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-md-8">

                @if(!$proizvodi)
                    <div>
                        <h1>No resoults</h1>
                    </div>
                @else
                    <h1>{{ $proizvodi->title }}</h1>
                    <p class="lead">{{$proizvodi->body}}</p>
                    <img src="{{asset('uploads/proizvodi/'.$proizvodi->image)}}"/>
            </div>
            <div class="col-md-4">
                <div class="well">
                    <dl class="dl-horizontal">
                        <dt>Креирано На:</dt>
                        <dd>{{date('M j, Y H:i',strtotime($proizvodi->created_at))}}</dd>
                    </dl>

                    <dl class="dl-horizontal">
                        <dt>Последна Промена На:</dt>
                        <dd>{{date('M j, Y H:i',strtotime($proizvodi->updated_at))}}</dd>
                    </dl>
                    <hr>

                    <div class="row">
                        <div class="col-sm-6">
                            <a href="{{route('proizvodi.edit',$proizvodi->id)}}"
                               class="btn btn-primary btn-block">Промени</a>

                        </div>

                        <div class="col-sm-6">

                            {!!Form::open(['route'=>['proizvodi.destroy',$proizvodi ->id],'method'=>'DELETE','enctype'=>"multipart/form-data"])!!}

                            {!!Form::submit('Избриши',['class'=>'btn btn-danger btn-block'])!!}

                            {!!Form::close()!!}
                        </div>
                    </div>


                </div>


            </div>
            @endif
        </div>
    </div>





@endsection