routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/Welcome', function () {
    return view('welcome');

});

Route::get('/', 'PagesController@getNewMain');

Route::resource('proizvodi','ProizvodiController');

Route::resource('pdf','PdfController');

Route::resource('galerija','GalleryController');

Route::resource('laminat','LaminatController');

Route::resource('stakleni','StakleniController');

Route::resource('lajsni','LajsniController');

Route::resource('ostanato','OstanatoController');

Route::resource('akcii','AkciiController');

Route::get('/informacii', 'PagesController@getInformacii');

Route::get('/contact', 'PagesController@getContact');

Route::post('/contact', 'PagesController@postContact');

Route::get('/sorabotka', 'PagesController@getSorabotka');

Route::post('/sorabotka', 'PagesController@postSorabotka');

Route::get('/template', 'PagesController@template');


Auth::routes(['register'=>true]);

Route::get('/home', 'HomeController@index')->name('home');


//STARI OVDEKA

Route::get('/main', 'PagesController@getMain');

app/Stakleni.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stakleni extends Model
{
    protected $table = 'stakleni';
}

app/Http/Controllers/StakleniController.php
<?php

namespace App\Http\Controllers;

use App\Stakleni;
use Illuminate\Http\Request;
use Session;

class StakleniController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    public function index()
    {
        $stakleni = Stakleni::orderBy('id', 'desc')->paginate(6);

        return view('stakleni.index', compact('stakleni'));
    }


    public function create()
    {
        return view('stakleni.create');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required',
            'image'=>'required|mimes:jpeg,jpg,bmp,png',
        ]);
        $image = $request->file('image');

        $slug = str_slug($request->title);

        if (isset($image)) {
            $imagename = $slug . '.' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!file_exists('uploads/stakleni')) {
                mkdir('uploads/stakleni', 0777, true);
            }
            $image->move('uploads/stakleni', $imagename);
        } else {
            $imagename = 'default.png';
        }


        $stakleni = new Stakleni();

        $stakleni->title = $request->title;
        $stakleni->body = $request->body;
        $stakleni->image = $imagename;
        $stakleni->save();

        Session::flash('success', 'Uspesno vnesuvajne');
        return redirect()->route('stakleni.show', $stakleni->id);
    }


    public function show($id)
    {
        $stakleni = Stakleni::find($id);

        return view('stakleni.show')->with('stakleni', $stakleni);
    }


    public function edit($id)
    {
        $stakleni = Stakleni::find($id);

        return view('stakleni.edit')->with('stakleni', $stakleni);
    }



    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title'=>'required',
            'image'=>'required|mimes:jpeg,jpg,bmp,png',
        ]);

        $stakleni = Stakleni::find($id);

        $image = $request->file('image');

        $slug = str_slug($request->title);

        if (isset($image)) {
            $imagename = $slug . '.' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!file_exists('uploads/stakleni')) {
                mkdir('uploads/stakleni', 0777, true);
            }
            unlink('uploads/stakleni/' . $stakleni->image);
            $image->move('uploads/stakleni', $imagename);
        } else {
            $imagename = $stakleni->image;
        }

        $stakleni->title = $request->input('title');
        $stakleni->body = $request->input('body');
        $stakleni->image = $imagename;

        $stakleni->save();

        Session::flash('success', 'Uspesno editirajne');

        return redirect()->route('stakleni.show', $stakleni->id);
    }

    public function destroy($id)
    {
        $stakleni = Stakleni::find($id);
        if (file_exists('uploads/stakleni/' . $stakleni->image)) {
            unlink('uploads/stakleni/' . $stakleni->image);
        }
        $stakleni->delete();

        Session::flash('success', 'Uspesno brisejne');

        return redirect()->route('stakleni.index');
    }
}

resources/views/stakleni/create.blade.php
@extends('NewDesign.template')

@section('title','Stakleni-create')

@section('create-content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Креирај продукт</h1>
            <hr>
            <form method="POST" enctype="multipart/form-data" action="{{ route('stakleni.store') }}">
                @csrf

                <div class="form-group">
                    <label name="title">Наслов:</label>
                    <input id="title" type="text" name="title"
                           class="form-control{{$errors->has('title') ? 'is-invalid' : ''}}"
                           value="{{ old('title') }}"
                           autocomplete="title" autofocus>
                    @if($errors->has('title'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('title') }}</strong>
                            </span>

                    @endif
                </div>

                <div class="form-group">
                    <label name="title">Опис:</label>
                    <textarea id="body" type="text" name="body"
                              class="form-control{{$errors->has('body') ? 'is-invalid' : ''}}"
                              value="{{ old('body') }}"
                              autocomplete="body" autofocus> </textarea>
                    @if($errors->has('body'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('body') }}</strong>
                            </span>

                    @endif
                </div>

                <div class="row">
                    <label for="image" class="col-md-4 col-form-label" >Прикачи Слика:</label>
                    <input type="file" class="form-control-file" id="image" name="image">
                    @if($errors->has('image'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{$errors->first('image') }}</strong>
                            </span>

                    @endif
                </div>
                <input type="submit" value="Креирај" class="btn btn-success btn-lg btn-block">

            </form>
        </div>
    </div>


@endsection

resources/views/stakleni/edit.blade.php
@extends ('NewDesign.template')

@section('title','stakleni-edit')

@section('create-content')
    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-md-12">
                {!! Form::model($stakleni, ['route' => ['stakleni.update', $stakleni->id],'method'=>'PUT','enctype'=>"multipart/form-data" ]) !!}
                <div class="container-fluid padding">
                    <div class="row padding">
                        <div class="col-md-8">
                            {{ Form::label('title', 'Наслов:') }}
                            {{ Form::text('title', null, ["class" => 'form-control']) }}

                            {{ Form::label('body', 'Опис') }}
                            {{ Form::textarea('body', null, ["class" => 'form-control']) }}

                            {{ Form::label('image', 'Прикачи Слика') }}
                            {{ Form::file('image', null, ["class" => 'form-control']) }}


                        </div>
                        <div class="col-md-4">
                            <div class="well">
                                <dl class="dl-horizontal">
                                    <dt>Креирано на:</dt>
                                    <dd>{{date('M j, Y H:i',strtotime($stakleni->created_at))}}</dd>
                                </dl>

                                <dl class="dl-horizontal">
                                    <dt>Последна промена на:</dt>
                                    <dd>{{date('M j, Y H:i',strtotime($stakleni->updated_at))}}</dd>
                                </dl>
                                <hr>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <a href="{{route('stakleni.show',$stakleni->id)}}"
                                           class="btn btn-danger btn-block">Откажи</a>

                                    </div>

                                    <div class="col-sm-6">
                                        {{Form::submit('Зачувај',['class'=>'btn btn-success btn-block',])}}

                                    </div>
                                </div>


                            </div>


                        </div>
                        {!! Form::close()!!}
                    </div>
                </div>






@endsection

resources/views/stakleni/index.blade.php
@extends('NewDesign.template')

@section('title','Ostanato')
@section('_pagetitle')
    <section class="page-title" style="background-image:url(images/title/2.jpg);">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Title -->
                <div class="title-column col-md-6 col-sm-8 col-xs-12">
                    <h1>Стаклени Блокови</h1>
                </div>
                <!--Bread Crumb -->
                <div class="breadcrumb-column col-md-6 col-sm-4 col-xs-12">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{{url('/')}}">Почетна</a></li>
                        <li class="active">Стаклени Блокови</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('create-content')
    <br>
    <div class="container-fluid padding">
        <div class="row padding">
            @auth
                <div class="col-md-2 offset-10 float-right">
                    <a href="{{route("stakleni.create")}}" class="btn btn-info float-right">Креирај Стаклени Блокови</a>
                </div>
            @endauth

        </div>
        <br>
        <section class="">
            <div class="auto-container">
                <!--Sec Title-->

                <div class="row clearfix">
                    @if($stakleni->count())
                        <div class="sec-title centered">
                            <h2>Стаклени Блокови</h2>
                        </div>
                        <br>
                        <br>
                        @foreach($stakleni as $staklenis)
                        <!--Services Block-->
                            <div class="services-block col-md-4 col-sm-6 col-xs-12" style="margin-top: 25px;margin-bottom: 25px">
                                <div class="inner-box">
                                    <div class="image">
                                        <a href="{{url('stakleni/'.$staklenis->id)}}"><img
                                                src="{{asset('uploads/stakleni/'.$staklenis->image)}}" style="height: 400px;width: 400px; object-fit: cover"
                                                alt=""/></a>
                                    </div>
                                    <div class="lower-box">
                                        <div class="content">
                                            <a href="{{url('stakleni/'.$staklenis->id)}}" class="arrow-box"><span
                                                    class="fa fa-angle-right"></span></a>
                                            <div class="text">{{$staklenis->title}}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    @else
                        <div class="container-fluid padding">
                            <div class="col-md-12">
                                <h1 class="text-center">Во Моментов Нема Производи Во Оваа Категорија.</h1>
                            </div>
                            @endif
                        </div>
                        <div class="text-center">
                            {!! $stakleni->links()!!}

                        </div>
                </div>
            </div>
            <br>
            <br>

@endsection

resources/views/stakleni/show.blade.php
@extends ('NewDesign.template')

@section('title','Stakleni-show')
@section('_pagetitle')
    <section class="page-title" style="background-image:url(../images/title/2.jpg);">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Title -->
                <div class="title-column col-md-6 col-sm-8 col-xs-12">
                    <h1>{{$stakleni->title}}</h1>
                </div>
                <!--Bread Crumb -->
                <div class="breadcrumb-column col-md-6 col-sm-4 col-xs-12">
                    <ul class="bread-crumb clearfix">
                        <li><a href="{{url('/')}}">Почетна</a></li>
                        <li class="active">Акции</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
@endsection


@section('create-content')
    <br>
    <!--Sidebar Page Container-->
    <div class="">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Sidebar Side-->
                <div class="sidebar-side col-lg-4 col-md-4 col-sm-12 col-xs-12">

                    <aside class="sidebar default-sidebar with-padding">

                        <!-- Sidebar Category -->
                        <div class="sidebar-widget sidebar-category">
                            <ul class="list">
                                <li><a href="{{url('/')}}">Почетна</a></li>
                                <li><a href="{{url('/akcii')}}">Акции</a></li>
                                <li><a href="{{url('/laminat')}}">Ламинат</a></li>
                                <li><a href="{{url('/pdf/1')}}">Внатрешни Врати</a></li>
                                <li><a href="{{url('/pdf/2')}}">Надворешни Врати</a></li>
                                <li><a href="{{url('/stakleni')}}">Стаклени Блокови</a></li>
                                <li><a href="{{url('/galerija')}}">Галерија</a></li>
                                <li><a href="{{url('/informacii')}}">Инфромации</a></li>
                                <li><a href="{{url('/kontakt')}}">Контакт</a></li>
                            </ul>
                        </div>

                        @auth
                            <div class="well">
                                <dl class="dl-horizontal">

                                    <dt>Креирано на:</dt>
                                    <dd>{{date('M j, Y H:i',strtotime($stakleni->created_at))}}</dd>
                                </dl>

                                <dl class="dl-horizontal">
                                    <dt>Последна промена на:</dt>
                                    <dd>{{date('M j, Y H:i',strtotime($stakleni->updated_at))}}</dd>
                                </dl>
                                <hr>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <a href="{{route('stakleni.edit',$stakleni->id)}}" class="btn btn-primary btn-block">Промени</a>

                                    </div>

                                    <div class="col-sm-6">

                                        {!!Form::open(['route'=>['stakleni.destroy',$stakleni->id],'method'=>'DELETE','enctype'=>"multipart/form-data"])!!}

                                        {!!Form::submit('Избриши',['class'=>'btn btn-danger btn-block'])!!}

                                        {!!Form::close()!!}

                                    </div>
                                </div>
                            </div>
                        @endauth


                    </aside>
                </div>
                <!--Content Side-->
                <div class="content-side col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <!--Services Single-->
                    <div class="service-single">
                        <div class="inner-box">
                            <div class="image">
                                <h3 class="text-center">{{$stakleni->title}}</h3>
                                <br>
                                <img src="{{asset('uploads/stakleni/'.$stakleni->image)}}" alt=""
                                     style="height: 400px;width: 400px; object-fit: cover; margin:auto"/>
                            </div>
                            <div class="lower-content">
                                <h3>Детални Информации</h3>
                                <div class="text">
                                    <p>{{$stakleni->body}}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

@endsection